stages:
  - build
  - deploy

build_portail:
  stage: build
  image: node:20
  script:
    - cd src/DispoFinder.Portail
    - npm ci
    - npm run build
  artifacts:
    paths:
      - src/DispoFinder.Portail/dist/

deploy_portail:
  stage: deploy
  image: node:20
  script:
    - npm install -g @azure/static-web-apps-cli
    - swa deploy src/DispoFinder.Portail/dist/dispo-finder.portail/browser --env production --deployment-token $AZURE_STATICWEBAPP_TOKEN
  only:
    - main
